spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001 #注册中心占用70011端口，冒号后面必须要有空格
spring:
  profile: dev
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001 #注册中心占用端口，冒号后面必须要有空格
spring:
  profiles: test
  application:
    name:  springcloud-config-eureka-client
# eureka自身配置
eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进入服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
